name: FirstAction

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20" # Specify the Node.js version you're using

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: sourcemovement
        run: sudo cp -r /home/ubuntu/actions-runner/dev/gym-website/gym-website/build/ * /var/www/html/dev
      
      # - name: service nginx restart
      #   run: sudo service nginx restart

      # - name: Verify routes and HTTP methods 
      #   run:  curl -X GET http://localhost:4200/api/test-route || echo "GET request failed"
      #         curl -X POST http://localhost:4200/api/test-route || echo "POST request failed"
      #         curl -X DELETE http://localhost:4200/api/test-route || echo "DELETE request failed"
      #   # Replace the URL with your server's URL or API endpoint, and repeat for other routes as needed.


