name: CI

on:
  push:
    branches:
      - main  

jobs:
  build:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3


    - name: Build project
      run: npm run build
      
     # name: sourcemovement
     # run: sudo cp -r /home/administrator/Live-Project/Live_Front/dev/_work/gym-website/build/ * /var/www/html
  
    - name: apache2restart
      run: sudo service apache2 restart
